[build]
  publish = "."

[[redirects]]
  from = "/platform"
  to = "/platform.html"
  status = 200

[[redirects]]
  from = "/why-vektor"
  to = "/why-vektor.html"
  status = 200

[[redirects]]
  from = "/what-we-are-not"
  to = "/what-we-are-not.html"
  status = 200

[[redirects]]
  from = "/unvarnished"
  to = "/unvarnished.html"
  status = 200

[[redirects]]
  from = "/founding-mandate"
  to = "/founding-mandate.html"
  status = 200

[[redirects]]
  from = "/story"
  to = "/story.html"
  status = 200

[[redirects]]
  from = "/research"
  to = "/research.html"
  status = 200

[[redirects]]
  from = "/documents"
  to = "/documents.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200
